name: Deploy to Amazon Linux (EC2)

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. CI 단계: 이미지를 빌드하고 도커 허브에 올리기
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 내려받기
        uses: actions/checkout@v3

      - name: QEMU 설정 (ARM 빌드 지원용)
        uses: docker/setup-qemu-action@v2

      - name: 도커 Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: 도커 허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 이미지 빌드 및 푸시 (ARM64)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-lucky:latest
          platforms: linux/arm64 # t4g 인스턴스를 위해 ARM64로 빌드!

  # 2. CD 단계: EC2에 들어가서 배포하기
  deploy:
    needs: build-and-push # 위 단계가 끝나야 실행됨
    runs-on: ubuntu-latest
    steps:
      - name: 코드 내려받기(설정 파일 전송을 위해 필요)
        uses: actions/checkout@v3

      - name: 설정 파일 복사(docker-compose.yaml, nginx.conf)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY}}
          source: "docker-compose.yaml, nginx.conf"
          target: "/home/ec2-user/"

      - name: EC2 접속 및 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user

            sudo docker-compose pull

            sudo docker-compose up -d --remove-orphans

            sudo docker image prune -f